version: '3.8'
services:
  messenger:
    build:
      context: .
    container_name: messenger_app
    ports:
      - "8080:8080" # Підключаємо порт
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=messenger
      - DB_USER=messenger_user
      - DB_PASSWORD=messenger_password
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:14
    container_name: messenger_db
    environment:
      POSTGRES_USER: messenger_user
      POSTGRES_PASSWORD: messenger_password
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
